# Generated by Django 4.2.4 on 2023-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='test4',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='test5',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='test6',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='test7',
            field=models.BooleanField(default=0),
        ),
    ]
